// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlServerMultipleCascade;

#nullable disable

namespace SqlServerMultipleCascade.Migrations
{
    [DbContext(typeof(EntityContextSQLServer))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SqlServerMultipleCascade.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParentEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentEntityId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("SqlServerMultipleCascade.Models.Entity", b =>
                {
                    b.HasOne("SqlServerMultipleCascade.Models.Entity", "ParentEntity")
                        .WithMany("ChildEntities")
                        .HasForeignKey("ParentEntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentEntity");
                });

            modelBuilder.Entity("SqlServerMultipleCascade.Models.Entity", b =>
                {
                    b.Navigation("ChildEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
